# Java Transactions Course compose file

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB:-transactions}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER:-myuser}'
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
